### ISSUE TITLE
支持自定义ip列表

### ISSUE THREAD

**Issue by gitiy1** [xianshenglu/cloudflare-ip-tester-app#17]
可以支持自定义测速ip段吗？例如增添一个读取自定义ip列表的csv文件的功能，实现起来应该还好，而且这样可以扩展该项目，使其不仅可以优选cloudflare的ip，还可以优选cloudfront和gcore之类的cdn的ip。

**Comment by xianshenglu** [comment]
> 可以支持自定义测速ip段吗？例如增添一个读取自定义ip列表的csv文件的功能，实现起来应该还好，而且这样可以扩展该项目，使其不仅可以优选cloudflare的ip，还可以优选cloudfront和gcore之类的cdn的ip。

不同 cdn 的测速地址是不是不一样？

如果赞多的话，可以考虑

**Comment by xianshenglu** [comment]
@gitiy1 https://github.com/xianshenglu/cloudflare-ip-tester-app/releases 0.6 版本在设置页面已经支持输入框自定义 Ipv4 列表
