### ISSUE TITLE
Display Issue in dark mode

### ISSUE THREAD

**Issue by nima2010** [xianshenglu/cloudflare-ip-tester-app#21]
when the device is in dark mode, table headers such as download speed and pings are not visible because their font colors are nearly the same as table background.
![1212](https://user-images.githubusercontent.com/6032182/224774086-f9b6e638-68a6-402e-a38a-4f538d86568e.jpg)

**Comment by xianshenglu** [comment]
@nima2010 Thanks for your information. I'll fix it in the next release.

**Comment by xianshenglu** [comment]
@nima2010 Fixed in v0.6 https://github.com/xianshenglu/cloudflare-ip-tester-app/releases
